// lib/data.ts

export interface Product {
  id: string;
  name: string;
  price: number;
  description: string;
  category: string;
  stock: boolean;
  imageUrl: string;
  colors: string[];
  sizes: string[];
  features: string[];
}

export const products: Product[] = [
  // --- HOODIES & SWEATSHIRTS ---
  {
    id: 'hp-001',
    name: 'Oversized Hoodie "Chaos"',
    price: 85.00,
    description: 'Sudadera oversized heavyweight (450gsm) en color negro lavado. Gráfico distorsionado en la espalda "CHAOS THEORY". Capucha amplia y caída de hombros exagerada para ese flow desinteresado.',
    category: 'Hoodies',
    stock: true,
    imageUrl: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?q=80&w=1000&auto=format&fit=crop',
    colors: ['Negro Lavado', 'Gris Ceniza'],
    sizes: ['S', 'M', 'L', 'XL'],
    features: ['450gsm Cotton', 'Oversized Fit', 'Drop Shoulders', 'Puff Print'],
  },
  {
    id: 'hp-002',
    name: 'Zip-Up Hoodie "Archive"',
    price: 95.00,
    description: 'Sudadera con cremallera completa y corte boxy. Acabado vintage con rotos sutiles en los puños. Diseño inspirado en el streetwear de los 2000.',
    category: 'Hoodies',
    stock: true,
    imageUrl: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?q=80&w=1000&auto=format&fit=crop',
    colors: ['Marrón Tierra', 'Negro'],
    sizes: ['M', 'L', 'XL'],
    features: ['Vintage Wash', 'Boxy Fit', 'YKK Zipper', 'Distressed Details'],
  },
  {
    id: 'hp-003',
    name: 'Crewneck "Essential"',
    price: 65.00,
    description: 'Cuello redondo básico pero con el fit perfecto. Corta en la cintura pero ancha de mangas. El básico definitivo para combinar con cargos.',
    category: 'Hoodies',
    stock: true,
    imageUrl: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?q=80&w=1000&auto=format&fit=crop',
    colors: ['Crema', 'Negro', 'Azul Cobalto'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    features: ['French Terry', 'Cropped Body', 'Elongated Sleeves'],
  },

  // --- TEES ---
  {
    id: 't-001',
    name: 'Graphic Tee "No Signal"',
    price: 45.00,
    description: 'Camiseta gráfica de corte cuadrado (boxy). Algodón grueso de 280gsm. Estampado delantero futurista con efecto glitch.',
    category: 'Tees',
    stock: true,
    imageUrl: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?q=80&w=1000&auto=format&fit=crop',
    colors: ['Blanco', 'Negro'],
    sizes: ['S', 'M', 'L', 'XL'],
    features: ['280gsm', 'Boxy Fit', 'High Neck Rib'],
  },
  {
    id: 't-002',
    name: 'Vintage Wash Tee',
    price: 40.00,
    description: 'Camiseta lisa con un proceso de teñido único que le da un aspecto desgastado. Suave al tacto y con caída pesada.',
    category: 'Tees',
    stock: true,
    imageUrl: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?q=80&w=1000&auto=format&fit=crop',
    colors: ['Gris Humo', 'Verde Oliva', 'Azul Medianoche'],
    sizes: ['S', 'M', 'L', 'XL'],
    features: ['Garment Dyed', 'Relajado', 'Soft Touch'],
  },
  {
    id: 't-003',
    name: 'Crop Top "Racer"',
    price: 35.00,
    description: 'Top corto ajustado de estilo deportivo. Tejido elástico que se adapta al cuerpo. Logo minimalista bordado en el pecho.',
    category: 'Tees',
    stock: true,
    imageUrl: 'https://images.unsplash.com/photo-1503341338985-c0477be52513?q=80&w=1000&auto=format&fit=crop',
    colors: ['Negro', 'Blanco', 'Rojo Fuego'],
    sizes: ['XS', 'S', 'M', 'L'],
    features: ['Stretchy', 'Fitted', 'Embroidered Logo'],
  },

  // --- PANTS ---
  {
    id: 'p-001',
    name: 'Parachute Pants "Tech"',
    price: 89.00,
    description: 'Pantalones paracaídas de nylon técnico. Volumen exagerado con cordones ajustables en cintura y tobillos. El sonido del movimiento.',
    category: 'Pantalones',
    stock: true,
    imageUrl: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?q=80&w=1000&auto=format&fit=crop',
    colors: ['Verde Militar', 'Negro', 'Gris Plata'],
    sizes: ['S', 'M', 'L'],
    features: ['Nylon', 'Oversized', 'Adjustable Toggles'],
  },
  {
    id: 'p-002',
    name: 'Baggy Jeans "90s"',
    price: 110.00,
    description: 'Vaqueros de corte muy ancho inspirados en el skate de los 90. Denim rígido de alta calidad que mejora con el uso.',
    category: 'Pantalones',
    stock: true,
    imageUrl: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?q=80&w=1000&auto=format&fit=crop',
    colors: ['Light Blue', 'Washed Black'],
    sizes: ['28', '30', '32', '34', '36'],
    features: ['Rigid Denim', 'Wide Leg', 'Baggy Fit'],
  },
  {
    id: 'p-003',
    name: 'Carpenter Pants',
    price: 95.00,
    description: 'Pantalones de trabajo con doble rodillera y bolsillo para metro. Corte recto y relajado. Resistentes y con estilo utilitario.',
    category: 'Pantalones',
    stock: false,
    imageUrl: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?q=80&w=1000&auto=format&fit=crop',
    colors: ['Beige Arena', 'Negro'],
    sizes: ['30', '32', '34', '36'],
    features: ['Canvas', 'Double Knee', 'Utility Pockets'],
  },
  {
    id: 'p-004',
    name: 'Jorts "Skater"',
    price: 70.00,
    description: 'Bermudas de jean extra anchas (Jorts) que caen por debajo de la rodilla. Imprescindibles para el verano y el look skater.',
    category: 'Pantalones',
    stock: true,
    imageUrl: 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?q=80&w=1000&auto=format&fit=crop',
    colors: ['Azul Medio', 'Negro'],
    sizes: ['30', '32', '34', '36'],
    features: ['Denim', 'Long Fit', 'Raw Hem'],
  },

  // --- JACKETS ---
  {
    id: 'j-001',
    name: 'Puffer Jacket "Cloud"',
    price: 180.00,
    description: 'Chaqueta de plumón sintético ultra voluminosa pero ligera. Cuello alto para protegerte del frío. Acabado mate.',
    category: 'Jackets',
    stock: true,
    imageUrl: 'https://images.unsplash.com/photo-1544923246-77307dd654cb?q=80&w=1000&auto=format&fit=crop',
    colors: ['Negro', 'Crema', 'Helado Azul'],
    sizes: ['S', 'M', 'L'],
    features: ['Water Resistant', 'Cropped Fit', 'High Collar'],
  },
  {
    id: 'j-002',
    name: 'Varsity Jacket "League"',
    price: 220.00,
    description: 'Chaqueta universitaria clásica con cuerpo de lana y mangas de piel vegana. Parches de chenilla por toda la prenda.',
    category: 'Jackets',
    stock: true,
    imageUrl: 'https://images.unsplash.com/photo-1559551409-dadc959f76b8?q=80&w=1000&auto=format&fit=crop',
    colors: ['Verde/Crema', 'Negro/Blanco'],
    sizes: ['M', 'L', 'XL'],
    features: ['Wool Blend', 'Vegan Leather Sleeves', 'Chenille Patches'],
  },
  {
    id: 'j-003',
    name: 'Racer Leather Jacket',
    price: 250.00,
    description: 'Chaqueta de cuero estilo motomami/biker. Ajustada y con protecciones estéticas en hombros y codos. Pura actitud.',
    category: 'Jackets',
    stock: true,
    imageUrl: 'https://images.unsplash.com/photo-1487222477894-8943e31ef7b2?q=80&w=1000&auto=format&fit=crop',
    colors: ['Negro', 'Rojo/Negro'],
    sizes: ['S', 'M', 'L'],
    features: ['Faux Leather', 'Slim Fit', 'Moto Details'],
  },

  // --- SHOES ---
  {
    id: 's-001',
    name: 'Chunky Sneaker "Titan"',
    price: 160.00,
    description: 'Zapatillas de suela gruesa y silueta agresiva. Inspiración retro-futurista con mix de materiales: malla, piel y goma.',
    category: 'Zapatos',
    stock: true,
    imageUrl: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?q=80&w=1000&auto=format&fit=crop',
    colors: ['Blanco/Gris', 'Negro Total'],
    sizes: ['38', '39', '40', '41', '42', '43', '44', '45'],
    features: ['Chunky Sole', 'Mixed Materials', 'Reflective Details'],
  },
  {
    id: 's-002',
    name: 'Combat Boots "Stomp"',
    price: 190.00,
    description: 'Botas militares de caña alta con suela track. Piel vegana resistente. Perfectas para pisar fuerte en la ciudad.',
    category: 'Zapatos',
    stock: true,
    imageUrl: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?q=80&w=1000&auto=format&fit=crop',
    colors: ['Negro Mate', 'Oxblood'],
    sizes: ['38', '39', '40', '41', '42', '43', '44', '45'],
    features: ['Vegan Leather', 'Track Sole', 'Side Zipper'],
  },

  // --- ACCESORIOS ---
  {
    id: 'a-001',
    name: 'Beanie "Fisherman"',
    price: 25.00,
    description: 'Gorro de lana corto estilo pescador. El toque final para cualquier outfit de invierno.',
    category: 'Accesorios',
    stock: true,
    imageUrl: 'https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?q=80&w=1000&auto=format&fit=crop',
    colors: ['Naranja Neón', 'Negro', 'Gris'],
    sizes: ['Talla Única'],
    features: ['Wool', 'Short Fit'],
  },
  {
    id: 'a-002',
    name: 'Tote Bag "Heavy"',
    price: 40.00,
    description: 'Bolsa tote de lona gruesa de algodón. Capacidad para llevar tu portátil y hoodies extra. Gráfico minimalista lateral.',
    category: 'Accesorios',
    stock: true,
    imageUrl: 'https://images.unsplash.com/photo-1544816155-12df9643f363?q=80&w=1000&auto=format&fit=crop',
    colors: ['Natural', 'Negro'],
    sizes: ['Talla Única'],
    features: ['Heavy Canvas', 'Inner Pocket', 'Printed'],
  },
  {
    id: 'a-003',
    name: 'Chunky Chain Necklace',
    price: 55.00,
    description: 'Collar de cadena cubana gruesa en acero inoxidable. No se oxida ni pierde color. Estética industrial.',
    category: 'Accesorios',
    stock: true,
    imageUrl: 'https://images.unsplash.com/photo-1611085583191-a3b181a88401?q=80&w=1000&auto=format&fit=crop',
    colors: ['Plata'],
    sizes: ['50cm'],
    features: ['Stainless Steel', 'Cuban Link'],
  },
  {
    id: 'a-004',
    name: 'Balaclava Distressed',
    price: 35.00,
    description: 'Pasamontañas de punto con efecto roto. Para los días más fríos o para fotos incógnito.',
    category: 'Accesorios',
    stock: true,
    imageUrl: 'https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?q=80&w=1000&auto=format&fit=crop',
    colors: ['Negro', 'Gris'],
    sizes: ['Talla Única'],
    features: ['Knit', 'Distressed Look'],
  }
];
